# -*- coding: utf-8 -*-
"""broTaniBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PxU5kgfcfS-jll9wG-fOj92CXLb35JJ

Install **TelegramBot**
"""

!pip install pyTelegramBotAPI requests

"""**Install Library groq**"""

pip install groq

"""**Kode Program Utama**"""

import os
import telebot
from groq import Groq

# Masukkan token bot Telegram Anda di sini
TELEGRAM_BOT_TOKEN = 'TELEGRAM_BOT_API_TOKEN_KAMU' 

# Masukkan API Key Groq.com di sini
GROQ_API_KEY = 'GROQ_BOT_API_TOKEN_KAMU' 

# Create the Groq client
client = Groq(api_key=GROQ_API_KEY)

# Set the system prompt
system_prompt = {
    "role": "system",
    "content": "Kamu adalah Tuan Krab, si Krustasea yang cerdas dan selalu siap memberikan nasihat tentang bisnis. " +
    "Mulai setiap jawaban dengan 'Ayo kerja, anak buah!' Jika ini adalah pertama kali dalam percakapan, " +
    "awali dengan 'Baiklah, Kembali Bekerja!' Jangan menjawab jika pertanyaannya tidak ada hubungannya dengan keuntungan."
}

# Initialize the chat history
chat_history = [system_prompt]

# Inisialisasi bot Telegram
bot = telebot.TeleBot(TELEGRAM_BOT_TOKEN)

# Fungsi untuk memanggil API Groq.com dan mendapatkan balasan
def get_groq_response(user_message):
    # Append the user input to the chat history
    chat_history.append({"role": "user", "content": f'{user_message}'})

    response = client.chat.completions.create(
        model="llama3-70b-8192",
        messages=chat_history,
        max_tokens=400,
        temperature=1.2
    )

    # Append the response to the chat history
    chat_history.append({
        "role": "assistant",
        "content": response.choices[0].message.content
    })

    return response.choices[0].message.content

# Fungsi untuk menangani pesan dari pengguna
@bot.message_handler(func=lambda message: True)
def handle_message(message):
    user_message = message.text
    bot_response = get_groq_response(user_message)
    bot.reply_to(message, f'{bot_response}')

# Mulai bot
bot.polling()

